import Foundation
import Testing

@testable import Core

/// P5.12 — recorded thermal scenarios against the composed engine.
///
/// A golden file freezes the full command sequence a scenario must produce.
/// The sequences were generated by this engine once, hand-reviewed at their
/// waypoints (the comments in each fixture say which), and frozen: from then
/// on any behavioural drift in any stage fails loudly here.
///
/// To re-record after an *intentional* behaviour change:
/// `GOLDEN_RECORD=1 swift test --filter Golden` prints the new sequences,
/// and the diff of the fixture files becomes part of the review.
private struct GoldenFixture: Decodable {
    struct Fan: Decodable {
        let id: Int
        let minimumRPM: Int
        let maximumRPM: Int
    }
    struct Sample: Decodable {
        let compute: [Double]
        let thermal: String?
    }
    let name: String
    let fan: Fan
    let profile: String
    let dtSeconds: Double
    let samples: [Sample]
    let expectedRPM: [Int]
}

@Suite("Golden thermal scenarios (P5.12)")
struct GoldenTests {

    private func run(_ fixtureName: String) throws {
        let url = try #require(
            Bundle.module.url(
                forResource: "Fixtures/\(fixtureName)", withExtension: "golden.json"))
        let fixture = try JSONDecoder().decode(GoldenFixture.self, from: Data(contentsOf: url))

        let profile = try #require(
            BuiltInProfiles.all().first(where: { $0.name == fixture.profile }))
        let fan = FanState(
            id: fixture.fan.id, name: "Fan", currentRPM: fixture.fan.minimumRPM,
            minimumRPM: fixture.fan.minimumRPM, maximumRPM: fixture.fan.maximumRPM,
            isPoweredOff: false)

        var state = Engine.State.initial
        var now = Date(timeIntervalSinceReferenceDate: 0)
        var produced: [Int] = []

        for sample in fixture.samples {
            now = now.addingTimeInterval(fixture.dtSeconds)
            let thermal = ThermalPressure(rawValue: sample.thermal ?? "nominal") ?? .nominal
            let cycle = Engine.step(
                Engine.Input(
                    profile: profile,
                    fans: [fan],
                    readingsByGroup: [.compute: sample.compute],
                    thermal: thermal,
                    now: now,
                    elapsedSeconds: fixture.dtSeconds),
                state: state)
            state = cycle.state
            produced.append(cycle.targets.first?.rpm ?? -1)
        }

        if ProcessInfo.processInfo.environment["GOLDEN_RECORD"] != nil {
            FileHandle.standardOutput.write(Data("GOLDEN \(fixture.name): \(produced)\n".utf8))
            return
        }

        #expect(produced.count == fixture.expectedRPM.count)
        for (index, pair) in zip(produced, fixture.expectedRPM).enumerated() {
            #expect(pair.0 == pair.1, "\(fixture.name) sample \(index): \(pair.0) != \(pair.1)")
        }
    }

    @Test("ramp, in-band oscillation plateau, limited descent")
    func rampPlateauDescent() throws {
        try run("ramp-plateau-descent")
    }

    @Test("a panic spike forces full speed and the hold outlives the recovery")
    func panicSpikeAndHold() throws {
        try run("panic-spike-hold")
    }

    @Test("the quiet profile's slew keeps every step inside its limits")
    func quietSlew() throws {
        try run("quiet-slew")
    }
}
